"""T014 — Alembic migration offline-SQL smoke + no-autogenerate guard.

A full upgrade→downgrade→upgrade round-trip against a live Postgres is gated
behind ``TEST_DATABASE_URL`` (set in CI when Postgres is reachable). The
always-on portion exercises alembic's offline SQL generation — catches
typos, missing imports, and bad revision ordering without needing a DB.
"""

from __future__ import annotations

import os
import subprocess
from pathlib import Path

import pytest

API_DIR = Path(__file__).resolve().parents[2]


def _alembic(*args: str, env: dict[str, str] | None = None) -> subprocess.CompletedProcess[str]:
    merged = {**os.environ, **(env or {})}
    return subprocess.run(
        [".venv/bin/alembic", *args],
        cwd=API_DIR,
        env=merged,
        capture_output=True,
        text=True,
        check=False,
    )


def test_alembic_offline_upgrade_sql_renders() -> None:
    """Offline SQL generation must succeed — validates DDL without a DB."""
    result = _alembic(
        "upgrade",
        "head",
        "--sql",
        env={"DATABASE_URL": "postgresql+psycopg2://x:x@localhost/x"},
    )
    assert result.returncode == 0, f"alembic offline upgrade failed: {result.stderr}"
    assert "CREATE TABLE users" in result.stdout
    assert "CREATE UNIQUE INDEX ix_users_email_lower ON users (LOWER(email))" in result.stdout
    assert "ux_users_pmdc_number" in result.stdout


@pytest.mark.skipif(
    not os.environ.get("TEST_DATABASE_URL"),
    reason="round-trip requires live Postgres via TEST_DATABASE_URL",
)
def test_alembic_roundtrip_live_postgres() -> None:
    db_url = os.environ["TEST_DATABASE_URL"]
    up1 = _alembic("upgrade", "head", env={"DATABASE_URL": db_url})
    assert up1.returncode == 0, up1.stderr
    down = _alembic("downgrade", "base", env={"DATABASE_URL": db_url})
    assert down.returncode == 0, down.stderr
    up2 = _alembic("upgrade", "head", env={"DATABASE_URL": db_url})
    assert up2.returncode == 0, up2.stderr


def test_no_autogenerate_in_versions() -> None:
    """Principle II: every migration is hand-reviewed; no --autogenerate."""
    versions_dir = API_DIR / "alembic" / "versions"
    for path in versions_dir.glob("*.py"):
        text = path.read_text(encoding="utf-8")
        assert "Alembic Revision Identifiers, generated automatically" not in text
        assert "# ### commands auto generated by Alembic" not in text
