"""T069 RED — Alembic migration round-trip for P1a (migrations 0003–0005).

Offline SQL smoke test always runs. Live round-trip requires TEST_DATABASE_URL.
Verifies: patients + enum types, vital_signs, lab_results tables exist and
have correct downgrade paths. Also extends the no-autogenerate guard to P1a
migration files.
"""

from __future__ import annotations

import os
import subprocess
from pathlib import Path

import pytest

API_DIR = Path(__file__).resolve().parents[2]


def _alembic(*args: str, env: dict[str, str] | None = None) -> subprocess.CompletedProcess[str]:
    merged = {**os.environ, **(env or {})}
    return subprocess.run(
        [".venv/bin/alembic", *args],
        cwd=API_DIR,
        env=merged,
        capture_output=True,
        text=True,
        check=False,
    )


def test_alembic_offline_upgrade_sql_p1a() -> None:
    """Offline SQL must include all P1a DDL — catches typos without a DB."""
    result = _alembic(
        "upgrade",
        "head",
        "--sql",
        env={"DATABASE_URL": "postgresql+psycopg2://x:x@localhost/x"},
    )
    assert result.returncode == 0, f"alembic offline upgrade failed:\n{result.stderr}"
    assert "CREATE TABLE patients" in result.stdout
    assert "CREATE TABLE vital_signs" in result.stdout
    assert "CREATE TABLE lab_results" in result.stdout
    assert "patient_sex" in result.stdout
    assert "patient_acuity" in result.stdout
    assert "patient_ward" in result.stdout
    assert "patient_status" in result.stdout


@pytest.mark.skipif(
    not os.environ.get("TEST_DATABASE_URL"),
    reason="round-trip requires live Postgres via TEST_DATABASE_URL",
)
def test_alembic_roundtrip_live_postgres_p1a() -> None:
    db_url = os.environ["TEST_DATABASE_URL"]

    up1 = _alembic("upgrade", "head", env={"DATABASE_URL": db_url})
    assert up1.returncode == 0, up1.stderr

    # verify tables
    check = subprocess.run(
        [
            "psql",
            db_url,
            "-c",
            (
                "SELECT table_name FROM information_schema.tables "
                "WHERE table_schema='public' AND table_name IN "
                "('patients','vital_signs','lab_results');"
            ),
        ],
        capture_output=True,
        text=True,
    )
    for tbl in ("patients", "vital_signs", "lab_results"):
        assert tbl in check.stdout, f"table {tbl} missing after upgrade"

    # verify enum types
    enum_check = subprocess.run(
        [
            "psql",
            db_url,
            "-c",
            (
                "SELECT typname FROM pg_type WHERE typname IN "
                "('patient_sex','patient_acuity','patient_ward','patient_status');"
            ),
        ],
        capture_output=True,
        text=True,
    )
    for etype in ("patient_sex", "patient_acuity", "patient_ward", "patient_status"):
        assert etype in enum_check.stdout, f"enum type {etype} missing after upgrade"

    down = _alembic("downgrade", "base", env={"DATABASE_URL": db_url})
    assert down.returncode == 0, down.stderr

    # verify tables gone
    check_down = subprocess.run(
        [
            "psql",
            db_url,
            "-c",
            (
                "SELECT table_name FROM information_schema.tables "
                "WHERE table_schema='public' AND table_name IN "
                "('patients','vital_signs','lab_results');"
            ),
        ],
        capture_output=True,
        text=True,
    )
    for tbl in ("patients", "vital_signs", "lab_results"):
        assert tbl not in check_down.stdout, f"table {tbl} still present after downgrade"

    up2 = _alembic("upgrade", "head", env={"DATABASE_URL": db_url})
    assert up2.returncode == 0, up2.stderr


def test_no_autogenerate_in_p1a_versions() -> None:
    """Principle II: P1a migrations must be hand-written (no --autogenerate)."""
    versions_dir = API_DIR / "alembic" / "versions"
    p1a_files = [
        versions_dir / "0003_patients.py",
        versions_dir / "0004_vital_signs.py",
        versions_dir / "0005_lab_results.py",
    ]
    for path in p1a_files:
        assert path.exists(), f"expected P1a migration at {path}"
        text = path.read_text(encoding="utf-8")
        assert "Alembic Revision Identifiers, generated automatically" not in text
        assert "# ### commands auto generated by Alembic" not in text
        count = text.lower().count("autogenerate")
        assert count == 0, f"{path.name} must not reference autogenerate; found {count}"
